server:
  port: 8080

spring:
  application:
    name: payment-platform
  jackson:
    default-property-inclusion: non_null
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding.yaml

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: payment-platform-producer-group

payment:
  mq:
    enabled: false
    pay-order-topic: pay.order.changed
    outbox-scan-batch-size: 100
    outbox-retry-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
